sudo: false
dist: trusty
language: python
python:
  - '2.7'

install:
  - make bootstrap

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

notifications:
  email: false
